In [1]:
# Our data management libraries
import pandas as pd
import numpy as np

# A basic visualization library
import matplotlib.pyplot as plt

# A great visualization library
import seaborn as sns

# Very important, this will make your charts appear in your notebook instead of in a new window.
%matplotlib inline

# lebel encoder
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv('../dataset/df_outlier_free_nov_03.csv')

df.head()

,Primary_Color,Sex,Age,Intake_Date,Intake_Condition,Intake_Type,days_stayed
0,BRN TABBY,Spayed,6,12/19/18,NORMAL,STRAY,799
1,BRN TABBY,Spayed,9,10/4/19,NORMAL,OWNER SURRENDER,760
2,ORG TABBY,Neutered,12,6/24/17,ILL MILD,STRAY,685
3,BRN TABBY,Neutered,8,7/13/17,NORMAL,STRAY,666
4,GRAY TABBY,Spayed,8,5/10/17,NORMAL,STRAY,661

In [3]:
# Initialize LabelEncoders for each categorical column
label_encoders = {}
for column in ['Primary_Color', 'Sex', 'Intake_Condition', 'Intake_Type']:
    label_encoders[column] = LabelEncoder()
    df[column + '_encoded'] = label_encoders[column].fit_transform(df[column])

# Define the transformer for other preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('scaler', StandardScaler(), ['Primary_Color_encoded', 'Sex_encoded', 'Intake_Condition_encoded', 'Intake_Type_encoded'])
        # Add more transformers for other columns if needed
    ],
    remainder='passthrough'  # Pass through the columns not specified
)

# Create a pipeline with LabelEncoder and other transformers
pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor)
])

# Fit and transform the data
transformed_data = pipeline.fit_transform(df)

# The transformed_data now contains the encoded and scaled values
print(transformed_data)

[[-0.6653780232763072 0.9364303842187641 0.3668044556127166 ... 'NORMAL'
  'STRAY' 799]
 [-0.6653780232763072 0.9364303842187641 0.3668044556127166 ... 'NORMAL'
  'OWNER SURRENDER' 760]
 [0.9454468817843004 -0.216991922985017 -1.911177259008151 ... 'ILL MILD'
  'STRAY' 685]
 ...
 [-0.6653780232763072 0.9364303842187641 0.7464680747161945 ...
  'UNDER AGE/WEIGHT' 'STRAY' 0]
 [-0.9496412418164145 0.9364303842187641 0.3668044556127166 ... 'NORMAL'
  'RETURN' 0]
 [0.2821660385240502 -0.216991922985017 -2.670504497215107 ...
  'FRACTIOUS' 'STRAY' 0]]

In [4]:
df.head(50)

,Primary_Color,Sex,Age,Intake_Date,Intake_Condition,Intake_Type,days_stayed,Primary_Color_encoded,Sex_encoded,Intake_Condition_encoded,Intake_Type_encoded
0,BRN TABBY,Spayed,6,12/19/18,NORMAL,STRAY,799,5,3,13,3
1,BRN TABBY,Spayed,9,10/4/19,NORMAL,OWNER SURRENDER,760,5,3,13,1
2,ORG TABBY,Neutered,12,6/24/17,ILL MILD,STRAY,685,22,2,7,3
3,BRN TABBY,Neutered,8,7/13/17,NORMAL,STRAY,666,5,2,13,3
4,GRAY TABBY,Spayed,8,5/10/17,NORMAL,STRAY,661,16,3,13,3
5,BROWN,Spayed,19,7/19/17,NORMAL,OWNER SURRENDER,660,7,3,13,1
6,WHITE,Spayed,5,8/4/18,NORMAL,STRAY,658,32,3,13,3
7,BLACK,Neutered,2,6/11/21,NORMAL,STRAY,615,0,2,13,3
8,BLACK,Neutered,2,6/11/21,NORMAL,STRAY,615,0,2,13,3
9,TAN,Neutered,8,6/3/21,NORMAL,WELFARE SEIZED,610,27,2,13,4
10,WHITE,Female,6,11/29/19,INJURED MILD,STRAY,530,32,0,10,3
11,GRAY TABBY,Spayed,7,12/15/17,NORMAL,STRAY,511,16,3,13,3
12,ORG TABBY,Neutered,2,5/12/21,UNDER AGE/WEIGHT,STRAY,484,22,2,14,3
13,ORG TABBY,Neutered,2,6/9/21,ILL MILD,STRAY,456,22,2,7,3
14,BLACK,Spayed,2,11/22/20,UNDER AGE/WEIGHT,STRAY,452,0,3,14,3
15,BLACK,Spayed,13,12/19/19,NORMAL,WELFARE SEIZED,434,0,3,13,4
16,BLACK,Female,2,7/9/21,NORMAL,STRAY,426,0,0,13,3
17,WHITE,Spayed,7,10/24/20,ILL MODERATETE,OWNER SURRENDER,409,32,3,8,1
18,BROWN,Neutered,6,12/31/17,NORMAL,STRAY,408,7,2,13,3
19,BRN TABBY,Spayed,2,5/13/21,UNDER AGE/WEIGHT,STRAY,398,5,3,14,3
20,GRAY,Female,2,8/25/21,NORMAL,STRAY,394,15,0,13,3
21,ORANGE,Neutered,5,1/23/21,ILL MILD,STRAY,390,21,2,7,3
22,WHITE,Spayed,7,6/26/19,NORMAL,STRAY,387,32,3,13,3
23,GRAY,Neutered,2,4/12/21,NORMAL,STRAY,366,15,2,13,3
24,BRN TABBY,Neutered,2,4/12/21,UNDER AGE/WEIGHT,STRAY,366,5,2,14,3
25,BLACK,Spayed,2,4/12/21,UNDER AGE/WEIGHT,STRAY,366,0,3,14,3
26,BRN TABBY,Neutered,2,4/12/21,UNDER AGE/WEIGHT,STRAY,366,5,2,14,3
27,BRN TABBY,Spayed,2,4/12/21,UNDER AGE/WEIGHT,STRAY,366,5,3,14,3
28,WHITE,Neutered,7,4/13/22,NORMAL,RETURN,345,32,2,13,2
29,GRAY TABBY,Spayed,9,7/18/17,NORMAL,STRAY,337,16,3,13,3
30,BLACK,Spayed,1,4/24/22,NORMAL,STRAY,334,0,3,13,3
31,GRAY,Female,9,8/6/17,NORMAL,STRAY,331,15,0,13,3
32,BLACK,Spayed,8,3/25/21,NORMAL,OWNER SURRENDER,329,0,3,13,1
33,GRAY,Spayed,4,5/5/22,NORMAL,OWNER SURRENDER,329,15,3,13,1
34,BRN TABBY,Neutered,7,4/9/18,FRACTIOUS,STRAY,327,5,2,5,3
35,BRN TABBY,Female,4,5/15/19,UNDER AGE/WEIGHT,STRAY,318,5,0,14,3
36,GRAY,Neutered,8,5/5/22,NORMAL,OWNER SURRENDER,316,15,2,13,1
37,BLACK,Male,6,7/30/17,UNDER AGE/WEIGHT,STRAY,314,0,1,14,3
38,GRAY TABBY,Male,4,5/19/19,UNDER AGE/WEIGHT,STRAY,314,16,1,14,3
39,BRN TABBY,Male,4,5/19/19,UNDER AGE/WEIGHT,STRAY,314,5,1,14,3
40,WHITE,Neutered,6,3/24/21,NORMAL,STRAY,308,32,2,13,3
41,BRN TABBY,Spayed,6,6/1/19,NORMAL,STRAY,307,5,3,13,3
42,BRN TABBY,Spayed,6,6/1/19,NORMAL,STRAY,307,5,3,13,3
43,GRAY,Neutered,2,6/12/21,NORMAL,OWNER SURRENDER,307,15,2,13,1
44,TORTIE DIL,Spayed,4,7/3/21,NORMAL,STRAY,305,30,3,13,3
45,GRAY,Neutered,2,11/7/21,UNDER AGE/WEIGHT,RETURN,305,15,2,14,2
46,WHITE,Spayed,5,5/3/20,ILL MILD,STRAY,298,32,3,7,3
47,BLACK,Neutered,9,4/3/17,NORMAL,STRAY,297,0,2,13,3
48,GRAY,Spayed,7,6/8/19,NORMAL,STRAY,294,15,3,13,3
49,WHITE,Spayed,9,3/15/19,NORMAL,OWNER SURRENDER,287,32,3,13,1

In [5]:
# Initialize a dictionary to store mappings
mappings = {}

# Use classes_ attribute to get the mapping
original_columns = ['Primary_Color', 'Sex', 'Intake_Condition', 'Intake_Type']
encoded_columns = ['Primary_Color_encoded', 'Sex_encoded', 'Intake_Condition_encoded', 'Intake_Type_encoded']

for col, encoded_col in zip(original_columns, encoded_columns):
    mappings[col] = dict(zip(label_encoders[col].classes_, label_encoders[col].transform(label_encoders[col].classes_)))

# Display the mappings
for col, mapping in mappings.items():
    print(f"{col} mapping:")
    print(mapping)
    print()

Primary_Color mapping:
{'BLACK': 0, 'BLK SMOKE': 1, 'BLK TABBY': 2, 'BLUE': 3, 'BLUE PT': 4, 'BRN TABBY': 5, 'BRN TIGER': 6, 'BROWN': 7, 'CALICO': 8, 'CALICO DIL': 9, 'CALICO TAB': 10, 'CHOC PT': 11, 'CREAM': 12, 'CRM TABBY': 13, 'FLAME PT': 14, 'GRAY': 15, 'GRAY TABBY': 16, 'GRAY TIGER': 17, 'LC LYNX PT': 18, 'LI LYNX PT': 19, 'LYNX PT': 20, 'ORANGE': 21, 'ORG TABBY': 22, 'S-T PT': 23, 'SEAL PT': 24, 'SLVR TABBY': 25, 'SNOWSHOE': 26, 'TAN': 27, 'TORBI': 28, 'TORTIE': 29, 'TORTIE DIL': 30, 'TRICOLOR': 31, 'WHITE': 32}

Sex mapping:
{'Female': 0, 'Male': 1, 'Neutered': 2, 'Spayed': 3}

Intake_Condition mapping:
{'AGED': 0, 'BEHAVIOR  MILD': 1, 'BEHAVIOR  MODERATE': 2, 'BEHAVIOR  SEVERE': 3, 'FERAL': 4, 'FRACTIOUS': 5, 'I/I REPORT': 6, 'ILL MILD': 7, 'ILL MODERATETE': 8, 'ILL SEVERE': 9, 'INJURED  MILD': 10, 'INJURED  MODERATE': 11, 'INJURED  SEVERE': 12, 'NORMAL': 13, 'UNDER AGE/WEIGHT': 14, 'WELFARE SEIZURES': 15}

Intake_Type mapping:
{'CONFISCATE': 0, 'OWNER SURRENDER': 1, 'RETURN': 2, 'STRAY': 3, 'WELFARE SEIZED': 4}

In [6]:
# Create DataFrames for each mapping
dfs = [pd.DataFrame({f"{col} (Original)": list(mapping.keys()), f"{encoded_col} (Encoded)": list(mapping.values())}) for col, mapping in mappings.items()]

# Concatenate DataFrames side by side
result_df = pd.concat(dfs, axis=1)

# Display the result DataFrame
print(result_df)

   Primary_Color (Original)  Intake_Type_encoded (Encoded) Sex (Original)  \
0                     BLACK                              0         Female
1                 BLK SMOKE                              1           Male
2                 BLK TABBY                              2       Neutered
3                      BLUE                              3         Spayed
4                   BLUE PT                              4            NaN
5                 BRN TABBY                              5            NaN
6                 BRN TIGER                              6            NaN
7                     BROWN                              7            NaN
8                    CALICO                              8            NaN
9                CALICO DIL                              9            NaN
10               CALICO TAB                             10            NaN
11                  CHOC PT                             11            NaN
12                    CREAM                             12            NaN
13                CRM TABBY                             13            NaN
14                 FLAME PT                             14            NaN
15                     GRAY                             15            NaN
16               GRAY TABBY                             16            NaN
17               GRAY TIGER                             17            NaN
18               LC LYNX PT                             18            NaN
19               LI LYNX PT                             19            NaN
20                  LYNX PT                             20            NaN
21                   ORANGE                             21            NaN
22                ORG TABBY                             22            NaN
23                   S-T PT                             23            NaN
24                  SEAL PT                             24            NaN
25               SLVR TABBY                             25            NaN
26                 SNOWSHOE                             26            NaN
27                      TAN                             27            NaN
28                    TORBI                             28            NaN
29                   TORTIE                             29            NaN
30               TORTIE DIL                             30            NaN
31                 TRICOLOR                             31            NaN
32                    WHITE                             32            NaN

    Intake_Type_encoded (Encoded) Intake_Condition (Original)  \
0                             0.0                        AGED
1                             1.0              BEHAVIOR  MILD
2                             2.0          BEHAVIOR  MODERATE
3                             3.0            BEHAVIOR  SEVERE
4                             NaN                       FERAL
5                             NaN                   FRACTIOUS
6                             NaN                  I/I REPORT
7                             NaN                    ILL MILD
8                             NaN              ILL MODERATETE
9                             NaN                  ILL SEVERE
10                            NaN               INJURED  MILD
11                            NaN           INJURED  MODERATE
12                            NaN             INJURED  SEVERE
13                            NaN                      NORMAL
14                            NaN            UNDER AGE/WEIGHT
15                            NaN            WELFARE SEIZURES
16                            NaN                         NaN
17                            NaN                         NaN
18                            NaN                         NaN
19                            NaN                         NaN
20                            NaN                         NaN
21                            NaN                         NaN
22                            NaN                         NaN
23                            NaN                         NaN
24                            NaN                         NaN
25                            NaN                         NaN
26                            NaN                         NaN
27                            NaN                         NaN
28                            NaN                         NaN
29                            NaN                         NaN
30                            NaN                         NaN
31                            NaN                         NaN
32                            NaN                         NaN

    Intake_Type_encoded (Encoded) Intake_Type (Original)  \
0                             0.0             CONFISCATE
1                             1.0        OWNER SURRENDER
2                             2.0                 RETURN
3                             3.0                  STRAY
4                             4.0         WELFARE SEIZED
5                             5.0                    NaN
6                             6.0                    NaN
7                             7.0                    NaN
8                             8.0                    NaN
9                             9.0                    NaN
10                           10.0                    NaN
11                           11.0                    NaN
12                           12.0                    NaN
13                           13.0                    NaN
14                           14.0                    NaN
15                           15.0                    NaN
16                            NaN                    NaN
17                            NaN                    NaN
18                            NaN                    NaN
19                            NaN                    NaN
20                            NaN                    NaN
21                            NaN                    NaN
22                            NaN                    NaN
23                            NaN                    NaN
24                            NaN                    NaN
25                            NaN                    NaN
26                            NaN                    NaN
27                            NaN                    NaN
28                            NaN                    NaN
29                            NaN                    NaN
30                            NaN                    NaN
31                            NaN                    NaN
32                            NaN                    NaN

    Intake_Type_encoded (Encoded)
0                             0.0
1                             1.0
2                             2.0
3                             3.0
4                             4.0
5                             NaN
6                             NaN
7                             NaN
8                             NaN
9                             NaN
10                            NaN
11                            NaN
12                            NaN
13                            NaN
14                            NaN
15                            NaN
16                            NaN
17                            NaN
18                            NaN
19                            NaN
20                            NaN
21                            NaN
22                            NaN
23                            NaN
24                            NaN
25                            NaN
26                            NaN
27                            NaN
28                            NaN
29                            NaN
30                            NaN
31                            NaN
32                            NaN

In [7]:
df.to_csv("../dataset/df_only_numeric_value_nov_05.csv", index = False)