# Trying gradient boosting algorithm

In [1]:
# Import our libraries 

# Pandas and numpy for data wrangling
import pandas as pd
import numpy as np

# Seaborn / matplotlib for visualization 
import seaborn as sns
sns.set()

import matplotlib.pyplot as plt
%matplotlib inline

# Helper function to split our data
from sklearn.model_selection import train_test_split

# Helper fuctions to evaluate our model.
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report, roc_auc_score, f1_score

In [2]:
df = pd.read_csv('dataset/df_only_numeric_value_nov_05.csv')
df.head()

,Primary_Color,Sex,Age,Intake_Date,Intake_Condition,Intake_Type,days_stayed,Primary_Color_encoded,Sex_encoded,Intake_Condition_encoded,Intake_Type_encoded
0,BRN TABBY,Spayed,6,12/19/18,NORMAL,STRAY,799,5,3,13,3
1,BRN TABBY,Spayed,9,10/4/19,NORMAL,OWNER SURRENDER,760,5,3,13,1
2,ORG TABBY,Neutered,12,6/24/17,ILL MILD,STRAY,685,22,2,7,3
3,BRN TABBY,Neutered,8,7/13/17,NORMAL,STRAY,666,5,2,13,3
4,GRAY TABBY,Spayed,8,5/10/17,NORMAL,STRAY,661,16,3,13,3

In [3]:
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error

# Load the dataset
df = pd.read_csv('dataset/df_only_numeric_value_nov_05.csv')

# Select relevant columns
selected_columns = ['Primary_Color_encoded', 'Sex_encoded', 'Intake_Condition_encoded', 'Intake_Type_encoded', 'days_stayed']
df_selected = df[selected_columns]

# Drop rows with missing values
df_selected = df_selected.dropna()

# Split the data into features (X) and target variable (y)
X = df_selected.drop('days_stayed', axis=1)
y = df_selected['days_stayed']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Gradient Boosting Regressor
gb_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# Fit the model to the training data
gb_model.fit(X_train, y_train)

# Make predictions on the test set
predictions = gb_model.predict(X_test)

# Evaluate the model
mse = mean_squared_error(y_test, predictions)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 5812.899903733605